site_name: Trabalho de Qualidade - AgroMart
theme:
  name: material
  language: pt-BR
  palette:
    - scheme: default
      primary: blue
      accent: light blue
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Modo Escuro
nav:
  - Home: index.md
  - Planejamento: planejamento.md
  - Fase 1 - Escopo e Metas: fase1.md
  - Fase 2 - GQM e Características: fase2.md
  - Fase 3 - Projeto da Avaliação: fase3.md
  - Fase 4 - Execução e Métricas: fase4.md
  - Apresentação: apresentacao.md

markdown_extensions:
  - attr_list
  - md_in_html
